
workspace 'HETSkinAnalysis.xcworkspace'
# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'HETSkinAnalysisDemo' do
    project 'HETSkinAnalysisDemo/HETSkinAnalysisDemo.xcodeproj'
    #pod 'QCloudCOSXML'
    pod 'QMUIKit'
    pod 'Masonry'
    pod 'YYKit'
end
